
import {Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Career Coach",
  description: "Generated by CareerX Team",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          />
        </head>

        <body className={`${inter.className} relative min-h-screen`}>
          {/* ✅ Background Grid + Gradient Layer */}
          <div className="grid-background" />

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Header */}
            <Header />

            {/* Main */}
            <main className="min-h-screen">{children}</main>
            <Toaster richColors/>

            {/* Footer */}

        <footer className="w-full bg-neutral-900 text-white pt-6 pb-6">
  <div className="container mx-auto px-6">

    {/* TOP SECTION */}
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 pb-6">

      {/* COLUMN 1 */}
      <div>
        <h2 className="text-2xl font-bold">
          <Image
            src="/logoo.png"
            alt="CareerX logo"
            width={200}
            height={60}
            className="h-14 py-1 w-auto object-contain"
          />
        </h2>
        <p className="text-sm text-gray-400">Your Personal Skill Coach</p>
      </div>

      {/* COLUMN 2 */}
      <div>
        <h3 className="font-semibold mb-2">Features</h3>
        <ul className="space-y-1 text-sm text-gray-400">
          <li>Learning Paths</li>
          <li>Skill Tracking</li>
          <li>AI Resume Builder</li>
          <li>Mock Interview AI</li>
        </ul>
      </div>

      {/* COLUMN 3 */}
      <div>
        <h3 className="font-semibold mb-2">Resources</h3>
        <ul className="space-y-1 text-sm text-gray-400">
          <li>Roadmaps</li>
          <li>Documentation</li>
          <li>Developer Guides</li>
          <li>FAQs</li>
        </ul>
      </div>

      {/* COLUMN 4 */}
      <div>
        <h3 className="font-semibold mb-2">Tech Stack</h3>
        <ul className="space-y-1 text-sm text-gray-400">
          <li>React.js</li>
          <li>Next.js</li>
          <li>Neon DB</li>
          <li>Prisma ORM</li>
        </ul>
      </div>
    </div>

    {/* DIVIDER */}
    <div className="border-t border-white/20 my-4"></div>

    {/* SOCIAL ICONS */}
    <div className="flex justify-center gap-4 text-2xl mb-3">
      <a href="https://github.com/Akashprajapati010" className="hover:text-blue-400 transition"><i className="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/akash-prajapati-521278256/" className="hover:text-blue-400 transition"><i className="fab fa-linkedin"></i></a>
      <a href="mailto:akashak5654@gmail.com" className="hover:text-red-400 transition">
        <i className="fas fa-envelope"></i>
      </a>
    </div>

    {/* COPYRIGHT */}
    <p className="text-center text-sm mt-2">
      © 2025 CareerX-AI | All Rights Reserved
    </p>

    {/* MADE WITH LOVE */}
    <p className="text-center text-sm mt-1">
      Made with <span className="text-red-600">❤️</span> by{" "}
      <span className="font-semibold text-blue-400">Akash Prajapati</span>
    </p>

  </div>
</footer>


          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
